# Generated by Django 4.1.7 on 2023-03-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.TextField()),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
